name = "openai-caching-proxy-worker"
main = "src/index.ts"
compatibility_date = "2022-12-11"

# This cloudflare worker uses either Upstash or workers KV to store cache.

# To use Upstash (hosted redis-over-REST),
# https://docs.upstash.com/redis/quickstarts/cloudflareworkers
# 
# 1. signing up for a free account at upstash.com, set your secrets below based on instructions
# here for `wrangler secret put` (or alternatively use the Cloudflare Workers web UI):
# https://developers.cloudflare.com/workers/platform/environment-variables/#adding-secrets-via-wrangler
# 2. Uncomment following environment variables config:
# [vars]
# - UPSTASH_REDIS_REST_TOKEN
# - UPSTASH_REDIS_REST_URL

# To use workers KV,
# 1. Run `wrangler kv:namespace create <YOUR_NAMESPACE>` in your terminal
# 2. Uncomment following config and fill in <YOUR_ID>:
kv_namespaces = [
   { binding = "OPENAI_CACHE", id = "deda714907f54fa88a1af9de6e558ebc", preview_id = "da60fe54aba544babad55db95d2b1e71" }
]

routes = [
	{ pattern = "proxy-hxvens.hirepros.ai", zone_id = "793f74f703991042eb3a2106788110ff", custom_domain = true },
	{ pattern = "proxy-hxvens.kerplunk.com", zone_id = "80a2564ec3e1038c36fd0e5d6209a948", custom_domain = true }
]